// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

// Mod
archives_base_name=MineColonies_Hordes
maven_group=steve_gall.minecolonies_hordes
mod_id=minecolonies_hordes
mod_version=1.2
mod_name=The Hordes addon for MineColonies
mod_description=Adjust 'The Hordes' mobs spawn position to outside of MineColonies.
mod_license=GPL 3.0
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-hordes
mod_source=https://github.com/gisellevonbingen-Minecraft/MineColonies_Hordes
mod_issues=https://github.com/gisellevonbingen-Minecraft/MineColonies_Hordes/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.9
neoforge_api_version_range=[21.1.0,)

// Required
minecolonies_version=1.1.874-1.21.1-snapshot
structurize_version=1.0.755-1.21.1-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
domumornamentum_file=5764083
domumornamentum_version=1.0.204-1.21.1-snapshot
blockui_version=1.0.192-1.21.1-snapshot
the_hordes_file=8014451
the_hordes_version=1.6.3
atlas_libs_file=5449009

// Optional

// Runtime Only
jei_version=19.19.6.235
jade_file=6155158
configured_file=5873783
journeymap_file=6124693
